// Prime Circle Group - Consolidated Dashboard Data - Multi-Month

export type MonthId = 'jan-2026' | 'feb-2026';

export const AVAILABLE_MONTHS = [
  { id: 'jan-2026' as MonthId, label: 'Janvier 2026' },
  { id: 'feb-2026' as MonthId, label: 'Février 2026' },
];

export const ENTITY_ROUTES = {
  agency: '/dashboard-prime-circle-agency/856d4617-0956-45f9-860e-baa0662e78e5',
  structuring: '/dashboard-prime-circle/84c179cf-20d2-4d56-b9b0-c6273cd3dd8b',
  digit: '/dashboard-digit/edb0ce96-ad6f-45bf-842a-8f237976ac4f',
};

// ============ JANUARY 2026 ============
const JAN_2026 = {
  monthLabel: 'Janvier 2026',
  footerLabel: 'Janvier 2026',

  // OVERVIEW
  overviewHero: [
    { label: "CA Groupe", value: "$198,900", detail: "5 entités consolidées", color: "navy", variance: null as string | null, varType: null as string | null },
    { label: "Marge Brute Groupe", value: "$89,607", detail: "45.0% du CA", color: "success", variance: null, varType: null },
    { label: "Résultat Net Holding", value: "$73,586", detail: "Après frais holding", color: "gold", variance: null, varType: null },
    { label: "Réserves Filiales", value: "$8,961", detail: "10% marge brute", color: "primary", variance: null, varType: null },
  ],
  overviewComparison: null as any[] | null,
  overviewComparisonTotal: null as any,
  entityCards: [
    { id: 'agency', name: 'Agency', badge: 'Media', gradient: 'linear-gradient(135deg, #4F5BD5 0%, #6366F1 100%)', cssClass: 'agency',
      metrics: [{ label: 'CA', value: '$10,726' }, { label: 'Marge Nette', value: '$2,245', colorClass: 'success' }], margin: 20.9, marginLevel: 'medium' as const },
    { id: 'structuring', name: 'Structuring', badge: 'Banking', gradient: 'linear-gradient(135deg, #1E3A5F 0%, #2D4A6F 100%)', cssClass: 'structuring',
      metrics: [{ label: 'CA', value: '$53,962' }, { label: 'Marge Nette', value: '$41,371', colorClass: 'success' }], margin: 76.7, marginLevel: 'high' as const },
    { id: 'digit', name: 'Digit Solution', badge: 'Ad Accounts', gradient: 'linear-gradient(135deg, #D946A8 0%, #EC4899 100%)', cssClass: 'digit',
      metrics: [{ label: 'CA', value: '$114,649' }, { label: 'Marge Nette', value: '$40,198', colorClass: 'success' }], margin: 35.1, marginLevel: 'medium' as const },
    { id: 'spy', name: 'SPY', badge: 'Tools', gradient: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)', cssClass: 'spy',
      metrics: [{ label: 'CA', value: '$16,750' }, { label: 'Marge Nette', value: '$3,262', colorClass: 'success' }], margin: 19.5, marginLevel: 'low' as const },
    { id: 'comment', name: 'Comment', badge: 'Trust', gradient: 'linear-gradient(135deg, #10B981 0%, #059669 100%)', cssClass: 'comment',
      metrics: [{ label: 'CA', value: '$2,813' }, { label: 'Marge Nette', value: '$2,531', colorClass: 'success' }], margin: 90.0, marginLevel: 'high' as const },
  ],
  consolidatedPL: [
    { label: 'Marge Nette Agency (après 50% Blink)', value: '$2,245', type: 'positive' },
    { label: 'Marge Nette Structuring', value: '$41,371', type: 'positive' },
    { label: 'Marge Nette Digit Solution', value: '$40,198', type: 'positive' },
    { label: 'Marge Nette SPY', value: '$3,262', type: 'positive' },
    { label: 'Marge Nette Comment/Trustpilot', value: '$2,531', type: 'positive' },
    { label: 'MARGE BRUTE GROUPE', value: '$89,607', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Réserves Filiales (10%)', value: '-$8,961', type: 'negative' },
    { label: 'REMONTÉE HOLDING (90%)', value: '$80,646', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Compta + CFO Groupe', value: '-$3,430', type: 'negative' },
    { label: 'Salaire Assistante', value: '-$1,630', type: 'negative' },
    { label: 'Salaires Fixes Sales', value: '-$2,000', type: 'negative' },
    { label: 'RÉSULTAT NET HOLDING', value: '$73,586', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Maxence (37.5%)', value: '-$27,595', type: 'negative' },
    { label: 'Thibault (37.5%)', value: '-$27,595', type: 'negative' },
    { label: '↳ dont Will', value: '$10,000', type: 'indent-muted' },
    { label: 'Florian (25%)', value: '-$18,396', type: 'negative' },
    { label: 'SALAIRES MANAGEMENT (100%)', value: '-$73,586', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'SOLDE HOLDING', value: '$0', type: 'highlight' },
  ],
  pieData: [
    { name: 'Agency ($2.2K)', value: 2245, color: '#F59E0B' },
    { name: 'Structuring ($41.4K)', value: 41371, color: '#1E3A5F' },
    { name: 'Digit Sol. ($40.2K)', value: 40198, color: '#4F5BD5' },
    { name: 'SPY ($3.3K)', value: 3262, color: '#10B981' },
    { name: 'Comment ($2.5K)', value: 2531, color: '#D946A8' },
  ],

  // AGENCY TAB
  agencyKPIs: [
    { label: 'CA Brut', value: '$10,726', detail: 'Abo + Setup', color: 'navy' },
    { label: 'Marge Nette', value: '$4,489', detail: '41.8% du CA', color: 'green' },
    { label: 'Part PCA (50%)', value: '$2,245', detail: 'Après split Blink', color: 'gold' },
    { label: 'Total Charges', value: '$6,237', detail: '58.2% du CA', color: 'pink' },
  ],
  agencyComparison: null as any[] | null,
  agencyWaterfall: [
    { label: 'CA Brut', value: '$10,726', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Coûts Setup (agents)', value: '-$1,300', type: 'negative' },
    { label: 'Salaires', value: '-$1,200', type: 'negative' },
    { label: 'Publicité', value: '-$1,038', type: 'negative' },
    { label: 'Com. Chris (10%)', value: '-$2,633', type: 'negative' },
    { label: 'Com. Master (5%)', value: '-$66', type: 'negative' },
    { label: 'TOTAL CHARGES', value: '-$6,237', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE (100%)', value: '$4,489', type: 'highlight' },
    { label: 'Part Blink (50%)', value: '-$2,245', type: 'negative' },
    { label: 'PART PCA (50%)', value: '$2,245', type: 'total-positive' },
  ],
  agencyRisks: [
    { label: 'Concentration Hugo', value: '60.8%', detail: 'du media dépensé', severity: 'danger' },
    { label: 'CL Exposure', value: '$21.0K', detail: 'media avancé', severity: 'danger' },
    { label: 'Marge Nette', value: '41.8%', detail: 'vs 54.8% en Dec', severity: 'warning' },
  ],

  // STRUCTURING TAB
  structuringKPIs: [
    { label: 'CA', value: '$53,962', detail: 'Moy. $1,384/client', color: 'navy' },
    { label: 'Marge Nette', value: '$41,371', detail: '76.7% du CA', color: 'green' },
    { label: 'Clients', value: '39', detail: 'Handled by Nathan', color: 'gold' },
    { label: 'Total Charges', value: '$12,591', detail: '23.3% du CA', color: 'pink' },
  ],
  structuringComparison: null as any[] | null,
  structuringWaterfall: [
    { label: 'CA', value: '$53,962', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Publicité (ADS)', value: '-$2,690', type: 'negative' },
    { label: 'Com. Sales Nathan', value: '-$4,213', type: 'negative' },
    { label: 'Com. Referral', value: '-$350', type: 'negative' },
    { label: 'Events', value: '-$1,000', type: 'negative' },
    { label: 'Coûts Fournisseurs', value: '-$4,338', type: 'negative' },
    { label: 'TOTAL CHARGES', value: '-$12,591', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE', value: '$41,371', type: 'highlight' },
  ],
  structuringServices: [
    { name: 'LLC Services', value: 19400, pct: '36%', status: 'Top' },
    { name: 'Physical Address US', value: 17700, pct: '33%', status: 'Top' },
    { name: 'AMEX', value: 8000, pct: '15%', status: 'Croissance' },
    { name: 'Autres Banking', value: 4848, pct: '9%', status: 'Stable' },
    { name: 'Revolut Business', value: 4014, pct: '7%', status: 'Stable' },
  ],

  // DIGIT TAB
  digitKPIs: [
    { label: 'CA', value: '$114,649', detail: 'Setup + Ad Account', color: 'navy' },
    { label: 'Marge Nette', value: '$40,198', detail: '35.1% du CA', color: 'green' },
    { label: 'Deals', value: '267', detail: '233 Setup + 34 Ad Account', color: 'gold' },
    { label: 'Total Charges', value: '$74,451', detail: '64.9% du CA', color: 'pink' },
  ],
  digitComparison: null as any[] | null,
  digitWaterfall: [
    { label: 'CA', value: '$114,649', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Coûts Fournisseurs', value: '-$29,708', type: 'negative' },
    { label: 'Com. Blink', value: '-$12,922', type: 'negative' },
    { label: 'Com. Sales', value: '-$3,190', type: 'negative' },
    { label: 'Salaires', value: '-$25,366', type: 'negative' },
    { label: 'Autres (Tools, Fees, Remb...)', value: '-$3,265', type: 'negative' },
    { label: 'TOTAL CHARGES', value: '-$74,451', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE', value: '$40,198', type: 'highlight' },
  ],
  digitRevenueBreakdown: [
    { name: 'Set-up', value: 77409, deals: '233', ticket: '$332' },
    { name: 'Ad Account', value: 27305, deals: '34', ticket: '$803' },
    { name: 'BM', value: 5651, deals: '—', ticket: '—' },
    { name: 'Page', value: 2770, deals: '—', ticket: '—' },
    { name: 'Autres', value: 1514, deals: '—', ticket: '—' },
  ],

  // SPY TAB
  spyKPIs: [
    { label: 'CA', value: '$16,750', detail: "Outils d'analyse", color: 'navy' },
    { label: 'Marge Nette', value: '$3,262', detail: '19.5% du CA', color: 'green' },
    { label: 'Deals', value: '5', detail: 'Licences SPY', color: 'gold' },
    { label: 'Total Charges', value: '$13,488', detail: '80.5% du CA', color: 'pink' },
  ],
  spyWaterfall: [
    { label: 'CA', value: '$16,750', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Coûts Produit/Licences', value: '-$11,250', type: 'negative' },
    { label: 'Com. Blink', value: '-$1,812', type: 'negative' },
    { label: 'Com. Sales', value: '-$425', type: 'negative' },
    { label: 'TOTAL CHARGES', value: '-$13,488', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE', value: '$3,262', type: 'highlight' },
  ],

  // COMMENT TAB
  commentKPIs: [
    { label: 'CA', value: '$2,813', detail: '16 Comment + 4 Trustpilot', color: 'navy' },
    { label: 'Marge Nette', value: '$2,531', detail: '90.0% du CA', color: 'green' },
    { label: 'Deals', value: '20', detail: '16 Comment + 4 Trustpilot', color: 'gold' },
    { label: 'Com. Sales', value: '$281', detail: '10.0% du CA', color: 'pink' },
  ],
  commentWaterfall: [
    { label: 'CA', value: '$2,813', type: 'positive' },
    { label: 'Coûts Produit', value: '$0', type: 'muted' },
    { label: 'Com. Sales (10%)', value: '-$281', type: 'negative' },
    { label: 'MARGE NETTE', value: '$2,531', type: 'highlight' },
  ],
  commentWarning: '',

  // HOLDING TAB
  holdingKPIs: [
    { label: 'Remontée Holding (90%)', value: '$80,646', detail: 'Bénéfices filiales', color: 'navy' },
    { label: 'Résultat Net Holding', value: '$73,586', detail: '100% distribué', color: 'gold' },
    { label: 'Réserves Filiales (10%)', value: '$8,961', detail: 'Trésorerie entités', color: 'green' },
    { label: 'Frais Holding', value: '$7,060', detail: 'Compta + Assist. + Sales', color: 'pink' },
  ],
  holdingComparison: null as any[] | null,
  holdingManagementFees: [
    { label: 'Prime Circle Agency', value: '$2,245', type: 'positive' },
    { label: 'Prime Circle Structuring', value: '$41,371', type: 'positive' },
    { label: 'Digit Solution', value: '$40,198', type: 'positive' },
    { label: 'SPY', value: '$3,262', type: 'positive' },
    { label: 'Comment/Trustpilot', value: '$2,531', type: 'positive' },
    { label: 'MARGE BRUTE GROUPE', value: '$89,607', type: 'total-positive' },
  ],
  holdingSynthese: [
    { label: 'MARGE BRUTE GROUPE', value: '$89,607', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Réserves Filiales (10%)', value: '-$8,961', type: 'negative', indent: true },
    { label: 'REMONTÉE HOLDING (90%)', value: '$80,646', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Compta + CFO', value: '-$3,430', type: 'negative', indent: true },
    { label: 'Salaire Assistante', value: '-$1,630', type: 'negative', indent: true },
    { label: 'Salaires Fixes Sales', value: '-$2,000', type: 'negative', indent: true },
    { label: 'RÉSULTAT NET HOLDING', value: '$73,586', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Salaires management (100%)', value: '-$73,586', type: 'negative', indent: true },
    { label: '↳ dont Will (via Thibault)', value: '$10,000', type: 'indent-muted', indent: true },
    { label: '', value: '', type: 'spacer' },
    { label: 'SOLDE HOLDING', value: '$0', type: 'highlight' },
  ],
  holdingPieData: [
    { name: 'Maxence ($27.6K)', value: 27595, color: '#1E3A5F' },
    { name: 'Thibault ($27.6K)', value: 27595, color: '#2D4A6F' },
    { name: 'Florian ($18.4K)', value: 18396, color: '#4F5BD5' },
    { name: 'Réserves Fil. ($9.0K)', value: 8961, color: '#C9A227' },
  ],
  directors: [
    { name: 'Maxence', pct: '37.5%', amount: '$27,595', gradient: 'linear-gradient(135deg, #1E3A5F 0%, #2D4A6F 100%)', subtitle: '' },
    { name: 'Thibault', pct: '37.5%', amount: '$27,595', gradient: 'linear-gradient(135deg, #1E3A5F 0%, #2D4A6F 100%)', subtitle: 'dont $10K Will' },
    { name: 'Florian', pct: '25%', amount: '$18,396', gradient: 'linear-gradient(135deg, #4F5BD5 0%, #6366F1 100%)', subtitle: '' },
  ],
  holdingNetResult: '$73,586',

  // YTD TAB (January only)
  ytdHero: [
    { label: "CA YTD", value: "$198,900", detail: "Janvier 2026", color: "navy" },
    { label: "Marge Brute YTD", value: "$89,607", detail: "45.0% du CA", color: "success" },
    { label: "Résultat Net YTD", value: "$73,586", detail: "Holding cumulé", color: "gold" },
    { label: "Réserves Cumulées", value: "$8,961", detail: "Toutes filiales", color: "primary" },
  ],
  ytdMonthlyTable: [
    { month: 'Janvier 2026', ca: '$198,900', margin: '$89,607', taux: '45.0%', net: '$73,586' },
  ],
  ytdMonthlyTotal: { month: 'YTD TOTAL', ca: '$198,900', margin: '$89,607', taux: '45.0%', net: '$73,586' },
  ytdEntityTable: [
    { entity: 'Agency (Part PCA)', jan: '$2,245', feb: '', ytd: '$2,245', pct: '2.5%' },
    { entity: 'Structuring', jan: '$41,371', feb: '', ytd: '$41,371', pct: '46.2%' },
    { entity: 'Digit Solution', jan: '$40,198', feb: '', ytd: '$40,198', pct: '44.9%' },
    { entity: 'SPY', jan: '$3,262', feb: '', ytd: '$3,262', pct: '3.6%' },
    { entity: 'Comment/Trustpilot', jan: '$2,531', feb: '', ytd: '$2,531', pct: '2.8%' },
  ],
  ytdEntityTotal: { entity: 'TOTAL GROUPE', jan: '$89,607', feb: '', ytd: '$89,607', pct: '100%' },
  ytdTrendData: [{ month: 'Janvier', ca: 198900, margin: 89607, net: 73586 }],

  // RESERVES TAB
  reservesHero: [
    { label: "Réserves Janvier", value: "$8,961", detail: "10% marge brute Jan", color: "navy" },
    { label: "Réserves YTD", value: "$8,961", detail: "Cumul 2026", color: "gold" },
  ],
  reservesEntityTable: [
    { entity: 'Agency (Part PCA)', jan: '$225', feb: '', ytd: '$225' },
    { entity: 'Structuring', jan: '$4,137', feb: '', ytd: '$4,137' },
    { entity: 'Digit Solution', jan: '$4,020', feb: '', ytd: '$4,020' },
    { entity: 'SPY', jan: '$326', feb: '', ytd: '$326' },
    { entity: 'Comment/Trustpilot', jan: '$253', feb: '', ytd: '$253' },
  ],
  reservesEntityTotal: { entity: 'TOTAL RÉSERVES', jan: '$8,961', feb: '', ytd: '$8,961' },
  reservesCards: [
    { name: 'Agency (Part PCA)', amount: '$225', pct: '2.5%' },
    { name: 'Structuring', amount: '$4,137', pct: '46.2%' },
    { name: 'Digit Solution', amount: '$4,020', pct: '44.9%' },
    { name: 'SPY', amount: '$326', pct: '3.6%' },
    { name: 'Comment/Trustpilot', amount: '$253', pct: '2.8%' },
  ],
};

// ============ FEBRUARY 2026 ============
const FEB_2026 = {
  monthLabel: 'Février 2026',
  footerLabel: 'Février 2026',

  overviewHero: [
    { label: "CA Groupe", value: "$258,543", detail: "6 entités consolidées", color: "navy", variance: "+30.0% vs Jan" as string | null, varType: "positive" as string | null },
    { label: "Marge Brute Groupe", value: "$112,431", detail: "43.5% du CA", color: "success", variance: "+25.5% vs Jan", varType: "positive" },
    { label: "Résultat Net Holding", value: "$94,128", detail: "Après frais holding", color: "gold", variance: "+27.9% vs Jan", varType: "positive" },
    { label: "Réserves Filiales", value: "$11,243", detail: "10% marge brute", color: "primary", variance: "+25.5% vs Jan", varType: "positive" },
  ],
  overviewComparison: [
    { entity: 'Agency (Part PCA 50%)', jan: '$2,244', feb: '$12,237', variation: '+445.5%', varType: 'positive', ytd: '$14,481' },
    { entity: 'Structuring', jan: '$41,371', feb: '$53,246', variation: '+28.7%', varType: 'positive', ytd: '$94,617' },
    { entity: 'Digit Solution', jan: '$40,198', feb: '$43,249', variation: '+7.6%', varType: 'positive', ytd: '$83,447' },
    { entity: 'SPY', jan: '$3,262', feb: '$3,559', variation: '+9.1%', varType: 'positive', ytd: '$6,821' },
    { entity: 'Comment/Trustpilot', jan: '$2,531', feb: '$140', variation: '-94.5%', varType: 'negative', ytd: '$2,671' },
  ] as any[] | null,
  overviewComparisonTotal: { entity: 'MARGE BRUTE GROUPE', jan: '$89,607', feb: '$112,431', variation: '+25.5%', varType: 'positive', ytd: '$202,038' },
  entityCards: [
    { id: 'agency', name: 'Agency', badge: 'Media', gradient: 'linear-gradient(135deg, #4F5BD5 0%, #6366F1 100%)', cssClass: 'agency',
      metrics: [{ label: 'CA', value: '$35,080' }, { label: 'Marge Nette', value: '$12,237', colorClass: 'success' }], margin: 34.9, marginLevel: 'medium' as const },
    { id: 'structuring', name: 'Structuring', badge: 'Banking', gradient: 'linear-gradient(135deg, #1E3A5F 0%, #2D4A6F 100%)', cssClass: 'structuring',
      metrics: [{ label: 'CA', value: '$73,500' }, { label: 'Marge Nette', value: '$53,246', colorClass: 'success' }], margin: 72.4, marginLevel: 'high' as const },
    { id: 'digit', name: 'Digit Solution', badge: 'Ad Accounts', gradient: 'linear-gradient(135deg, #D946A8 0%, #EC4899 100%)', cssClass: 'digit',
      metrics: [{ label: 'CA', value: '$122,330' }, { label: 'Marge Nette', value: '$43,249', colorClass: 'success' }], margin: 35.4, marginLevel: 'medium' as const },
    { id: 'spy', name: 'SPY', badge: 'Tools', gradient: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)', cssClass: 'spy',
      metrics: [{ label: 'CA', value: '$27,300' }, { label: 'Marge Nette', value: '$3,559', colorClass: 'success' }], margin: 13.0, marginLevel: 'low' as const },
    { id: 'comment', name: 'Comment', badge: 'Trust', gradient: 'linear-gradient(135deg, #10B981 0%, #059669 100%)', cssClass: 'comment',
      metrics: [{ label: 'CA', value: '$333' }, { label: 'Marge Nette', value: '$140', colorClass: 'success' }], margin: 42.0, marginLevel: 'medium' as const },
  ],
  consolidatedPL: [
    { label: 'Marge Nette Agency (après 50% Blink)', value: '$12,237', type: 'positive' },
    { label: 'Marge Nette Structuring', value: '$53,246', type: 'positive' },
    { label: 'Marge Nette Digit Solution', value: '$43,249', type: 'positive' },
    { label: 'Marge Nette SPY', value: '$3,559', type: 'positive' },
    { label: 'Marge Nette Comment/Trustpilot', value: '$140', type: 'positive' },
    { label: 'MARGE BRUTE GROUPE', value: '$112,431', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Réserves Filiales (10%)', value: '-$11,243', type: 'negative' },
    { label: 'REMONTÉE HOLDING (90%)', value: '$101,188', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Compta + CFO Groupe', value: '-$3,430', type: 'negative' },
    { label: 'Salaire Assistante', value: '-$1,630', type: 'negative' },
    { label: 'Salaires Fixes Sales', value: '-$2,000', type: 'negative' },
    { label: 'RÉSULTAT NET HOLDING', value: '$94,128', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Maxence (37.5%)', value: '-$35,298', type: 'negative' },
    { label: 'Thibault (37.5%)', value: '-$35,298', type: 'negative' },
    { label: '↳ dont Will', value: '$10,000', type: 'indent-muted' },
    { label: 'Florian (25%)', value: '-$23,532', type: 'negative' },
    { label: 'SALAIRES MANAGEMENT (100%)', value: '-$94,128', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'SOLDE HOLDING', value: '$0', type: 'highlight' },
  ],
  pieData: [
    { name: 'Agency ($12.2K)', value: 12237, color: '#F59E0B' },
    { name: 'Structuring ($53.2K)', value: 53246, color: '#1E3A5F' },
    { name: 'Digit Sol. ($43.2K)', value: 43249, color: '#4F5BD5' },
    { name: 'SPY ($3.6K)', value: 3559, color: '#10B981' },
    { name: 'Comment ($140)', value: 140, color: '#D946A8' },
  ],

  agencyKPIs: [
    { label: 'CA Brut', value: '$35,080', detail: '+227% vs Jan ($10,726)', color: 'navy' },
    { label: 'Marge Nette', value: '$24,473', detail: '69.8% du CA', color: 'green' },
    { label: 'Part PCA (50%)', value: '$12,237', detail: 'Après split Blink', color: 'gold' },
    { label: 'Total Charges', value: '$10,606', detail: '30.2% du CA', color: 'pink' },
  ],
  agencyComparison: [
    { indicator: 'CA Brut', jan: '$10,726', feb: '$35,080', variation: '+227.0%', varType: 'positive' },
    { indicator: 'Marge Nette', jan: '$4,489', feb: '$24,473', variation: '+445.2%', varType: 'positive' },
    { indicator: 'Part PCA (50%)', jan: '$2,244', feb: '$12,237', variation: '+445.4%', varType: 'positive' },
    { indicator: 'Media Géré', jan: '$279,691', feb: '$515,952', variation: '+84.5%', varType: 'positive' },
    { indicator: 'Transactions', jan: '62', feb: '145', variation: '+133.9%', varType: 'positive' },
  ] as any[] | null,
  agencyWaterfall: [
    { label: 'CA Brut', value: '$35,080', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Publicité (Ads)', value: '-$6,666', type: 'negative' },
    { label: 'Coûts Setup', value: '-$2,500', type: 'negative' },
    { label: 'Salaires', value: '-$1,200', type: 'negative' },
    { label: 'Com. Master Referral', value: '-$211', type: 'negative' },
    { label: 'Com. No Limit Referral', value: '-$30', type: 'negative' },
    { label: 'TOTAL CHARGES', value: '-$10,606', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE (100%)', value: '$24,473', type: 'highlight' },
    { label: 'Part Blink (50%)', value: '-$12,237', type: 'negative' },
    { label: 'PART PCA (50%)', value: '$12,237', type: 'total-positive' },
  ],
  agencyRisks: [
    { label: 'Concentration Salmech', value: '25.6%', detail: 'du media dépensé', severity: 'warning' },
    { label: 'CL Exposure', value: '$211K', detail: 'x10 vs Jan', severity: 'danger' },
    { label: 'Marge Nette', value: '69.8%', detail: 'vs 41.8% en Jan', severity: 'success' },
  ],

  structuringKPIs: [
    { label: 'CA', value: '$73,500', detail: '+38.4% vs Jan', color: 'navy' },
    { label: 'Marge Nette', value: '$53,246', detail: '72.4% du CA', color: 'green' },
    { label: 'Clients', value: '53', detail: '+35.9% vs Jan (39)', color: 'gold' },
    { label: 'Total Charges', value: '$20,254', detail: '27.6% du CA', color: 'pink' },
  ],
  structuringComparison: [
    { indicator: 'CA', jan: '$53,962', feb: '$73,500', variation: '+36.2%', varType: 'positive' },
    { indicator: 'Marge Nette', jan: '$41,371', feb: '$53,246', variation: '+28.7%', varType: 'positive' },
    { indicator: 'Taux de Marge', jan: '76.7%', feb: '72.4%', variation: '-4.3pts', varType: 'negative' },
    { indicator: 'Clients', jan: '39', feb: '53', variation: '+35.9%', varType: 'positive' },
    { indicator: 'Ticket Moyen', jan: '$1,384', feb: '$1,387', variation: '+0.2%', varType: 'positive' },
  ] as any[] | null,
  structuringWaterfall: [
    { label: 'CA', value: '$73,500', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Publicité (ADS)', value: '-$4,525', type: 'negative' },
    { label: 'Com. Sales Nathan', value: '-$5,498', type: 'negative' },
    { label: 'Coûts Fournisseurs', value: '-$10,181', type: 'negative' },
    { label: 'Frais Bancaires', value: '-$50', type: 'negative' },
    { label: 'TOTAL CHARGES', value: '-$20,254', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE', value: '$53,246', type: 'highlight' },
  ],
  structuringServices: [
    { name: 'LLC Services', value: 19400, pct: '36%', status: 'Top' },
    { name: 'Physical Address US', value: 17700, pct: '33%', status: 'Top' },
    { name: 'AMEX', value: 8000, pct: '15%', status: 'Croissance' },
    { name: 'Autres Banking', value: 4848, pct: '9%', status: 'Stable' },
    { name: 'Revolut Business', value: 4014, pct: '7%', status: 'Stable' },
  ],

  digitKPIs: [
    { label: 'CA', value: '$122,330', detail: '+6.7% vs Jan ($114,649)', color: 'navy' },
    { label: 'Marge Nette', value: '$43,249', detail: '35.4% du CA', color: 'green' },
    { label: 'Deals', value: '213', detail: '170 Setup + 43 Ad Account', color: 'gold' },
    { label: 'Total Charges', value: '$79,081', detail: '64.6% du CA', color: 'pink' },
  ],
  digitComparison: [
    { indicator: 'CA', jan: '$114,649', feb: '$122,330', variation: '+6.7%', varType: 'positive' },
    { indicator: 'Marge Nette', jan: '$40,198', feb: '$43,249', variation: '+7.6%', varType: 'positive' },
    { indicator: 'Taux de Marge', jan: '35.1%', feb: '35.4%', variation: '+0.3pts', varType: 'positive' },
    { indicator: 'Deals', jan: '225', feb: '213', variation: '-5.3%', varType: 'negative' },
    { indicator: 'Ticket Moyen', jan: '$509', feb: '$574', variation: '+12.7%', varType: 'positive' },
  ] as any[] | null,
  digitWaterfall: [
    { label: 'CA', value: '$122,330', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Coûts Fournisseurs', value: '-$33,906', type: 'negative' },
    { label: 'Com. Blink', value: '-$12,912', type: 'negative' },
    { label: 'Com. Sales', value: '-$2,656', type: 'negative' },
    { label: 'Salaires', value: '-$21,971', type: 'negative' },
    { label: 'Autres (Tools, Fees, Refunds, BizExp)', value: '-$7,636', type: 'negative' },
    { label: 'TOTAL CHARGES', value: '-$79,081', type: 'total-negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE', value: '$43,249', type: 'highlight' },
  ],
  digitRevenueBreakdown: [
    { name: 'Set-up', value: 77409, deals: '170', ticket: '$455' },
    { name: 'Ad Account', value: 27305, deals: '43', ticket: '$635' },
    { name: 'BM', value: 5651, deals: '—', ticket: '—' },
    { name: 'Page', value: 2770, deals: '—', ticket: '—' },
    { name: 'Autres', value: 1514, deals: '—', ticket: '—' },
  ],

  spyKPIs: [
    { label: 'CA', value: '$27,300', detail: '+63.0% vs Jan ($16,750)', color: 'navy' },
    { label: 'Marge Nette', value: '$3,559', detail: '13.0% du CA', color: 'green' },
    { label: 'Deals', value: '5', detail: 'Licences SPY', color: 'gold' },
    { label: 'Total Charges', value: '$23,741', detail: '87.0% du CA', color: 'pink' },
  ],
  spyWaterfall: [
    { label: 'CA', value: '$27,300', type: 'positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Total Charges', value: '-$23,741', type: 'negative' },
    { label: '', value: '', type: 'spacer' },
    { label: 'MARGE NETTE', value: '$3,559', type: 'highlight' },
  ],

  commentKPIs: [
    { label: 'CA', value: '$333', detail: '-88.2% vs Jan ($2,813)', color: 'navy' },
    { label: 'Marge Nette', value: '$140', detail: '42.0% du CA', color: 'green' },
    { label: 'Deals', value: '20', detail: '16 Comment + 4 Trustpilot', color: 'gold' },
    { label: 'Total Charges', value: '$193', detail: '58.0% du CA', color: 'pink' },
  ],
  commentWaterfall: [
    { label: 'CA', value: '$333', type: 'positive' },
    { label: 'Coûts Produit', value: '$0', type: 'muted' },
    { label: 'Total Charges', value: '-$193', type: 'negative' },
    { label: 'MARGE NETTE', value: '$140', type: 'highlight' },
  ],
  commentWarning: "Activité en forte baisse ce mois. CA divisé par ~8 vs janvier.",

  holdingKPIs: [
    { label: 'Remontée Holding (90%)', value: '$101,188', detail: 'Bénéfices filiales', color: 'navy' },
    { label: 'Résultat Net Holding', value: '$94,128', detail: '100% distribué', color: 'gold' },
    { label: 'Réserves Filiales (10%)', value: '$11,243', detail: 'Trésorerie entités', color: 'green' },
    { label: 'Frais Holding', value: '$7,060', detail: 'Compta + Assist. + Sales', color: 'pink' },
  ],
  holdingComparison: [
    { indicator: 'Marge Brute Groupe', jan: '$89,607', feb: '$112,431', variation: '+25.5%', varType: 'positive' },
    { indicator: 'Réserves Filiales (10%)', jan: '$8,961', feb: '$11,243', variation: '+25.5%', varType: 'positive' },
    { indicator: 'Remontée Holding (90%)', jan: '$80,646', feb: '$101,188', variation: '+25.5%', varType: 'positive' },
    { indicator: 'Frais Holding', jan: '$7,060', feb: '$7,060', variation: '0%', varType: 'neutral' },
    { indicator: 'Résultat Net Holding', jan: '$73,586', feb: '$94,128', variation: '+27.9%', varType: 'positive' },
  ] as any[] | null,
  holdingManagementFees: [
    { label: 'Prime Circle Agency', value: '$12,237', type: 'positive' },
    { label: 'Prime Circle Structuring', value: '$53,246', type: 'positive' },
    { label: 'Digit Solution', value: '$43,249', type: 'positive' },
    { label: 'SPY', value: '$3,559', type: 'positive' },
    { label: 'Comment/Trustpilot', value: '$140', type: 'positive' },
    { label: 'MARGE BRUTE GROUPE', value: '$112,431', type: 'total-positive' },
  ],
  holdingSynthese: [
    { label: 'MARGE BRUTE GROUPE', value: '$112,431', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Réserves Filiales (10%)', value: '-$11,243', type: 'negative', indent: true },
    { label: 'REMONTÉE HOLDING (90%)', value: '$101,188', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Compta + CFO', value: '-$3,430', type: 'negative', indent: true },
    { label: 'Salaire Assistante', value: '-$1,630', type: 'negative', indent: true },
    { label: 'Salaires Fixes Sales', value: '-$2,000', type: 'negative', indent: true },
    { label: 'RÉSULTAT NET HOLDING', value: '$94,128', type: 'total-positive' },
    { label: '', value: '', type: 'spacer' },
    { label: 'Salaires management (100%)', value: '-$94,128', type: 'negative', indent: true },
    { label: '↳ dont Will (via Thibault)', value: '$10,000', type: 'indent-muted', indent: true },
    { label: '', value: '', type: 'spacer' },
    { label: 'SOLDE HOLDING', value: '$0', type: 'highlight' },
  ],
  holdingPieData: [
    { name: 'Maxence ($35.3K)', value: 35298, color: '#1E3A5F' },
    { name: 'Thibault ($35.3K)', value: 35298, color: '#2D4A6F' },
    { name: 'Florian ($23.5K)', value: 23532, color: '#4F5BD5' },
    { name: 'Réserves Fil. ($11.2K)', value: 11243, color: '#C9A227' },
  ],
  directors: [
    { name: 'Maxence', pct: '37.5%', amount: '$35,298', gradient: 'linear-gradient(135deg, #1E3A5F 0%, #2D4A6F 100%)', subtitle: 'vs $27,595 Jan (+27.9%)' },
    { name: 'Thibault', pct: '37.5%', amount: '$35,298', gradient: 'linear-gradient(135deg, #1E3A5F 0%, #2D4A6F 100%)', subtitle: 'dont $10K Will' },
    { name: 'Florian', pct: '25%', amount: '$23,532', gradient: 'linear-gradient(135deg, #4F5BD5 0%, #6366F1 100%)', subtitle: 'vs $18,396 Jan (+27.9%)' },
  ],
  holdingNetResult: '$94,128',

  ytdHero: [
    { label: "CA YTD", value: "$457,443", detail: "Jan + Fév 2026", color: "navy" },
    { label: "Marge Brute YTD", value: "$202,038", detail: "44.2% du CA", color: "success" },
    { label: "Résultat Net YTD", value: "$167,714", detail: "Holding cumulé", color: "gold" },
    { label: "Réserves Cumulées", value: "$20,204", detail: "Toutes filiales", color: "primary" },
  ],
  ytdMonthlyTable: [
    { month: 'Janvier 2026', ca: '$198,900', margin: '$89,607', taux: '45.1%', net: '$73,586' },
    { month: 'Février 2026', ca: '$258,543', margin: '$112,431', taux: '43.5%', net: '$94,128' },
  ],
  ytdMonthlyTotal: { month: 'YTD TOTAL', ca: '$457,443', margin: '$202,038', taux: '44.2%', net: '$167,714' },
  ytdEntityTable: [
    { entity: 'Agency (Part PCA)', jan: '$2,245', feb: '$12,237', ytd: '$14,482', pct: '7.2%' },
    { entity: 'Structuring', jan: '$41,371', feb: '$53,246', ytd: '$94,617', pct: '46.8%' },
    { entity: 'Digit Solution', jan: '$40,198', feb: '$43,249', ytd: '$83,447', pct: '41.3%' },
    { entity: 'SPY', jan: '$3,262', feb: '$3,559', ytd: '$6,821', pct: '3.4%' },
    { entity: 'Comment/Trustpilot', jan: '$2,531', feb: '$140', ytd: '$2,671', pct: '1.3%' },
  ],
  ytdEntityTotal: { entity: 'TOTAL GROUPE', jan: '$89,607', feb: '$112,431', ytd: '$202,038', pct: '100%' },
  ytdTrendData: [
    { month: 'Janvier', ca: 198900, margin: 89607, net: 73586 },
    { month: 'Février', ca: 258543, margin: 112431, net: 94128 },
  ],

  reservesHero: [
    { label: "Réserves Janvier", value: "$8,961", detail: "10% marge brute Jan", color: "navy" },
    { label: "Réserves Février", value: "$11,243", detail: "10% marge brute Fév", color: "success" },
    { label: "Réserves YTD", value: "$20,204", detail: "Cumul 2026", color: "gold" },
    { label: "Croissance", value: "+25.5%", detail: "Fév vs Jan", color: "primary" },
  ],
  reservesEntityTable: [
    { entity: 'Agency (Part PCA)', jan: '$224', feb: '$1,224', ytd: '$1,448' },
    { entity: 'Structuring', jan: '$4,137', feb: '$5,325', ytd: '$9,462' },
    { entity: 'Digit Solution', jan: '$4,020', feb: '$4,325', ytd: '$8,345' },
    { entity: 'SPY', jan: '$326', feb: '$356', ytd: '$682' },
    { entity: 'Comment/Trustpilot', jan: '$253', feb: '$14', ytd: '$267' },
  ],
  reservesEntityTotal: { entity: 'TOTAL RÉSERVES', jan: '$8,961', feb: '$11,243', ytd: '$20,204' },
  reservesCards: [
    { name: 'Agency (Part PCA)', amount: '$1,448', pct: '7.2%' },
    { name: 'Structuring', amount: '$9,462', pct: '46.8%' },
    { name: 'Digit Solution', amount: '$8,345', pct: '41.3%' },
    { name: 'SPY', amount: '$682', pct: '3.4%' },
    { name: 'Comment/Trustpilot', amount: '$267', pct: '1.3%' },
  ],
};

export type PCGroupMonthData = typeof FEB_2026;

export function getMonthData(month: MonthId): PCGroupMonthData {
  return month === 'jan-2026' ? JAN_2026 as PCGroupMonthData : FEB_2026;
}
